### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by karmanyaahm**
As previously discussed in the Matrix room, I have this deployment thing. ATM it deploys to both IPFS and GH Pages, though IPFS hosting won't be useful to the project directly unless there's a domain. But, other people can access it from IPFS, so I don't know if you want to keep that feature. 

Apart from that, on a git tag, this will create a release and output zip and tar.gz files for anyone self-hosting the frontend. It also builds and tests every pull request. The deployment to GH Pages and IPFS only happens when there's no "-" in the git tag. For example, v1.0.0-alpha1 won't trigger a deployment, whereas v1.0.0 will.

Also, if accepted, these changes will need to be `Squash and Merge`d because there are too many commits. @toger5 any feedback on how you would want this to work? I know this wasn't discussed this extensively in the Matrix room, I just designed something that seemed appropriate and think could help.

### CODE REVIEW

**Comment by toger5** [comment]
Nice this is super cool!
The pages deployment looks to stay the same as before `./dist` from the webpack build becomes `./` on the `pagers` branch. What about the pages theme yaml and the about.md file. (the about.md file is copied as part of the webpack build so that should be fine. (The _config.yml on the other hand is not. should i just add that to the webpack build.) 
For now they are useless anyways. But I want this to become a landing page for TheBoard.

**Comment by toger5** [comment]
I also like the no deploy on "-" I still could publish the alpha right? I would than just need to tag it as 0.x.x and not 0.x.x-alpha.
This might be a good solutions. the tags would than not be able to show that this is a prerelease version. But in the app itself I could still show the version number as alpha.

**Comment by toger5** [comment]
squashing would be really nice indeed!
Other than that this looks really nice and helpful to me!

**Comment by karmanyaahm** [comment]
> The pages deployment looks to stay the same as before `./dist` from the webpack build becomes `./` on the `pagers` branch. What about the pages theme yaml and the about.md file. (the about.md file is copied as part of the webpack build so that should be fine. (The _config.yml on the other hand is not. should i just add that to the webpack build.)

Is there supposed to be a _config.yml in the main branch; or is it manually added? If it's manually added, it would be helpful to copy it as part of the webpack build.

>  I would than just need to tag it as 0.x.x and not 0.x.x-alpha.

Yes, 0.x.x should still be published. It's just anything containing a "-".

**Comment by toger5** [comment]
How to deal with the .gitignore file? Is that still necassary? Or will only the files copied be part of the commit anyways? The ignore file would be nice to be at least able to upload a new verision from my computer as well.

**Comment by karmanyaahm** [comment]
> How to deal with the .gitignore file? Is that still necassary? Or will only the files copied be part of the commit anyways? The ignore file would be nice to be at least able to upload a new verision from my computer as well.

ATM it's just copying the dist folder as is. I can add a line to copy the gitignore as well?

**Pull request merged**
